### ISSUE TITLE
Google fonts are used for small stretches of text

### ISSUE THREAD

**Issue by r-rrrr-r** [Anna-Saratovskaia/sergeisaratovsky.com#1]
The website uses Google fonts for small, unchanging stretches of text. These fonts are loaded from a third party, causing an increase in page size and requiring another connection to be made.

If the styled text was replaced with SVG curves, it would be possible to reduce overall page size without sacrificing much maintainability.

**Comment by Anna-Saratovskaia** [comment]
Created two SVG files for substituting styled text in the header (logo and main header). Changed styled text to SVG files, deleted Google fonts from html.
