### ISSUE TITLE
Code nitpicking

### ISSUE THREAD

**Issue by r-rrrr-r** [Anna-Saratovskaia/sergeisaratovsky.com#10]
- [ ] bioTestimonials css file seems to join two separate things - biography (main and side section) and testimonials. Should it be split?
- [x] testimonial-text wrappers seem to be unneeded, as you could style paragraphs in testimonials.
- [x] The .home class seems to be used for the container with several .card elements. I suggest renaming it to .cards
- [x] While all other sections are styled based on a class, testimonials uses an ID for targeting its CSS. This boosts the specificity of testimonial-related rules, but also makes CSS less reusable, as it is forever tied to a unique ID. Please explain in a follow-up comment why you chose to use an ID to style it.
- [x] Page fails HTML validation. If you choose not to fix all the errors, please leave a comment explaining your justification.
- [x] Lots of pointless empty lines in HTML that do not seem to be useful.
- [x] Small pieces of text separated from their li opening and closing tags on separate lines.
- [x] Indentation of HTML is wacky - offsets of opening tags often do not match the closing ones.
- [x] You refer to contact section as #cta (short for Call to Action). A button might be a call to action, but the contact form it sends the user to is not. I would suggest changing this name to something more descriptive, e.g. #contact.
- [x] Your CSS uses font weights of 400, 500, 600 and 700. I don't think Calibri offers any intermediate weights between normal (400) and bold (700), so any intermediate values probably render either 400 or 700 anyway. I suggest replacing intermediate values with the ones that are actually available in the font.

**Comment by Anna-Saratovskaia** [comment]
Delete wrappers but left class .testimonial-text by adding it to the next level div.

**Comment by Anna-Saratovskaia** [comment]
I used the id-selector in testimonial section because this is how I understood the task of simplifying selectors of this section.

**Comment by Anna-Saratovskaia** [comment]
Tried to put  li opening and closing tags on the same line with the text - Prettier formatter doesn't allow to do this.
