### ISSUE TITLE
Make links to top of the page use an explicit fragment identifier

### ISSUE THREAD

**Issue by r-rrrr-r** [Anna-Saratovskaia/sergeisaratovsky.com#4]
Currently, links to the top of the page use href="#". They do perform their function correctly. However, I'd like to suggest changing them to some explicit fragment identifier (e.g. '#start' or '#top').

The reason is that href="#" is commonly used on links that should have their default behavior ignored and replaced with JavaScript handler. If you include links like that in the page, it is unclear to someone inspecting the site if they are supposed to have bring to top behavior or are a leftover after some kind of handler got removed. An explicit fragment identifier makes their purpose more clear.

**Comment by Anna-Saratovskaia** [comment]
Thanks a lot for your comment on using href="#" to be replaced with JS handler. Changed href="#" to href="#top".
