### ISSUE TITLE
Clean up the image folder

### ISSUE THREAD

**Issue by r-rrrr-r** [Anna-Saratovskaia/sergeisaratovsky.com#5]
Some files in image folder are not used (e.g. sakura). Some are older versions of SVG resources that serve no purpose. Untitled.pdn is a reduntant older copy for main logo image. PSD documents have names that do not match the generated files.

**Comment by Anna-Saratovskaia** [comment]
Deleted images which are not used, named PSD files in accordance with the names of generated files.
