### ISSUE TITLE
CSS cleanup sweep

### ISSUE THREAD

**Issue by r-rrrr-r** [Anna-Saratovskaia/sergeisaratovsky.com#7]
bioTestimonials.css
    at-a-glance looks like it wants to be a component, but the things inside are named in inconsistent ways.
    Styling of raw dt and dd. Got to limit the scope to the proper component or make it general CSS.
    Separation of styling of dt and .year, w2hich are the same element.
    \<span class="heading-secondary"\>
    heading-secondary-box is used for centering its only child. There is no need for it. text-align: center on the header will be enough
    Many \<p class="bio-text"\> instead of styling them based on the parent.
    Why should there even be an .education to center a header that is centered elsewhere?
    at-a-glance-icon does not exist in HTML
    .carousel-container no longer exists in HTML
    There is no more code to set transform-animation class

contactForm.css
    Has a block comment for footer stuff that is gone now
    Bundles stuff for Thank You page. I would suggest separating that out into a separate stylesheet, to be used by Thank You page alone.

general.css
    Looks okay for the most part
    Youtube video styling is too complicated. There are a bunch of containers, all to size the iframes and give them correct 16/9 proportions. This looks like code that was copy/pasted from some ancient source. Today, we do not need the percentage padding and position: absolute trick, as we can use aspect-ratio property.

hero.css
    Almost all good. One nitpick - you are mixing .heading-text and .aristotle-quote with the hero section code. If those are integral components of hero section, give them more BEM-like classes that forever tie them to that section. If they are independent mini components, they should not be surrounded by hero section code on both sides. You could peel all the wrappers around youtube iframes and style only the iframe[src*='youtube.com'] selector

modals.css
    There is little need for Modals comment in the beginning of a modals.css file
    Many selectors are repeated, providing for two different sets of modal classes. Seems like unifying them will simplify things.

pageFooter.css
    Quite reasonable and focused on its purpose

pageHeader.css
    body--sticky-header class is no longer used to keep header pinned. It was switched to position: fixed
    Thus, the whole sticky header section is not needed

queries.css
    Did not evaluate, it looks like a mix between work in progress and old remnants of something

teaching.css
    A fair bit of flotsam and overly vague naming
        .teaching and .experience is styled, but does not exist
        Generic styles for all ul and h4 elements in a component file - got to make them more specific or change into a general stylesheet
        .icon-teaching does not exist in the document
        Individual \<img\> elements that represent a single teaching icon are given a class teaching-icons. Probably should not be plural

Other
    \<ion-icon name="close-outline"\>\</ion-icon\> is the last of ion icons. If you remove it, you could get rid of their JS.
    Smooth scroll JS is probably not needed. You have the declaration on html to make scrolling smooth, and if the browser is too old to understand it, just let things scroll in a jumpy way.

**Comment by r-rrrr-r** [comment]
Most of these issues were fixed as part of https://github.com/Anna-Saratovskaia/sergeisaratovsky.com/commit/028992be4afdd230e88904df01d8386a993b69ea . The ones I see remaining are
- [x] Youtube iframe sizing wrappers
- [x] Modal closing icon not replaced with SVG yet
- [x] Third party JS dependencies still there
- [x] Footer links do not appear link-like until hovered over
- [x] Lack of margins between major page sections
- [x] .teaching-icon still has a translateY trick that you got rid of for checkboxes
- [x] Lots of places have to set font size to 1.8rem, Would it be better to make it the default for the whole page? This would let you get rid of things like teaching-experience class that exist only because default font size is off. You can still keep 1rem = 10px as a convenience unit if you set 1.8rem global font size on body.
- [x] font-family: "ZCOOL KuaiLe" referencing the font you already removed
- [x] Styling of things inside testimonial-box leans heavy on classes where tag names could be cleaner
- [x] testimonial-text p:first-child works well for 2 paragraphs, but will fail to add space if there are 3 or more. Try to make a different selector that hits all paragraphis except the last one.
- [x] testimonial-author has a paragraph with a bold tag that looks like it is eager to become a header

I will look through the new version of the code and see if anything else is there to be done.

**Comment by Anna-Saratovskaia** [comment]
Size Youtube iframe, add attribute selector
