### ISSUE TITLE
Biography code dies on exception

### ISSUE THREAD

**Issue by r-rrrr-r** [Anna-Saratovskaia/sergeisaratovsky.com#8]
Biography modal initialization dies halfway through, and fails to open the modal on click of "Read More"
Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
    at script.js:20:15

The failure is caused by script.js expecting to have some teaching philosophy content that was missing. To make it right, either (a) remove teaching philosophy references, (b) harden the philosophy-related code to tolerate missing philosophy element, or (c) unify classes, so that there would be no need to add new classes whether you have 1, 2 or 19 modals.

**Comment by Anna-Saratovskaia** [comment]
Chosen 'c' variant

**Comment by r-rrrr-r** [comment]
You have said that you chose (c), but you actually did (a). To do (c), you need to keep track of multiple fullModalText elements instead of just one, and have Read More buttons specify which modal they want to open (for example, by referencing modal id in a data attribute). Implementing this would be a good JS exercise, but is not required for the site launch.

**Comment by Anna-Saratovskaia** [comment]
I ll implement c-variant when elaborate Teaching philosophy section.
