### ISSUE TITLE
Space and font size visual mismatches

### ISSUE THREAD

**Issue by r-rrrr-r** [Anna-Saratovskaia/sergeisaratovsky.com#9]
- [x] Teaching Experience header is probably too close to the text below. If you look at the space from the beginning of the Teaching Experience box to the first line of plain text within, the header seems to favor the bottom part of that space, leaving a lot of free space on top and little on bottom.
- [x] A lot of empty shaded area at the bottom of Teaching Experience section. A more reasonable amount would be closer in size to free space on top and on sides 
- [x] Testimonials header is way smaller than Teaching and has way less space around it, even though both of them occupy a similar place in your page structure. Unless there is a good reason to keep the different, I suggest reconciling them to be more alike size and spacing-wise.
- [x] Verity Leung ends up having the last word of her description wrap down to last line, alone.
- [x] Ava Music graphic is of lower resolution that the size you render it, causing it to get a bit fuzzy due to upsampling.
- [x] Ava Music testimonial is shorter than its left column, causing the testimonial header and text to render in the middle of the box. While centering is shorter looks right on the portrait and name sidebar, the main part of testimonial will probably look better top aligned
- [x] The About section sidebar is extended in height to match the column on left, and so ends up with a lengthy beaver tail of background without content. I suggest letting it end at the bottom of the content.
- [x] The Your Message textarea is resizable. When it increases in width, it first takes space away from the fields to its left, and shrinks the image on right only when name and email fields are shrunk into uselessness. Since the image is purely decorative, it would be better to protect the fields on left from shrinking and go immediately to shrinking the image.
- [x] Field labels are rather far from the fields themselves. A label should be closer to the field it is referencing, while yours are almost halfway between two fields.
- [x] New Students are welcome! header is a bit too close to the form labels below.
- [x] The footer seems a bit too close to the form. In other places, you keep your sections a bit more apart.

**Comment by r-rrrr-r** [comment]
You checked off the first item (teaching experience header) without actually pushing the code that changes it.

Generally speaking, you should check off items as done only after you pushed your code that fixes the problem. Having it work better somewhere on your computer does not count. If you think that the request is wrong and no code change is needed, provide an explanation for why the current way is better and the change should be avoided.

**Comment by Anna-Saratovskaia** [comment]
Ava Music testimonials looks ever more weird if top aligned. Instead, deleted one line in the author description so the left part became a bit shorter.

**Comment by Anna-Saratovskaia** [comment]
I plan to put a teaching philosophy modal at the end of About sidebar so I leave its length as it is for now.
